// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylyzkqxjfymgozaqfaee.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlseXprcXhqZnltZ296YXFmYWVlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3ODIxMDcsImV4cCI6MjA2ODM1ODEwN30.OXt10BgQ111k6Ki8vWPWmZct08DIWc73_teW9ADs6eY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});